### ISSUE TITLE
Update compiler to solc 0.5

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-contracts#110]
# Bounty :

## Scope 
- Upgrade solidity v0.5.2
- Upgrade Truffle v5
- Upgrade ganache-cli v6.2.5
- Upgrade OpenZeppelin release-v2.1.0-solc-0.5
- just upgrade compiler and build environment, don't change interfaces
- you can copy from here: https://github.com/leapdao/solEVM-enforcer/commit/414d73f5002e66749468c20786084696bf360ba4

## Deliverables
- code and passing tests
- run integration tests and make sure they fly

## Gain for the project
- more strict compiler, less bugs.

## Roles: 
bounty gardener: name / 10% 
bounty worker: name / 80%
bounty reviewer: name / 10%

**Comment by troggy** [comment]
this might require to fork some of the files from zOs, because they don't support OZ 2.* yet. Like @eshavkun did here https://github.com/leapdao/network-governance/pull/18
