### ISSUE TITLE
prevent reducing epochLength below number of active validators in posOperator contract

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-contracts#120]
# Bounty

Currently you could set `epochLength` to a number less then validator set size and by that lock the stake of some validator.

## Scope

- figure out the way to prevent setting epoch length smaller than a largest slotId taken
- implement the change
- add unit tests

## Deliverables

- updated contracts
- updated tests

## Gain for the project

prevent reward loss for the validators

## Roles
bounty gardener: @troggy / 30 DAI
bounty worker: @troggy / 75%
bounty reviewer: name / 25%

## Funded by

Dev Circle

**Comment by troggy** [comment]
@johannbarbie I guess, we are not supporting slot gaps, right? 

E.g. Given there are 6 validators on slots 0 to 5 and epochLength of 6. If validator on slot 4 is logged out and slot 4 is free now (owned by 0x0), we cannot set epochLength to 5. Even if there are 5 validators now
