### ISSUE TITLE
allow to finalize multiple exits 

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-contracts#123]
to reduce grieving attack with a lot of small outputs inserted before my output.

## Deliverables
The finalise exit function loops over up to 20 exits.

## Gain for the project
Reduce fees -> more usable.

## Roles: 
bounty gardener: @eezcjkr  / 10% 
bounty worker: @eezcjkr  / 75% 
bounty reviewer: @troggy  / 15%

**Comment by eezcjkr** [comment]
Should also change the stake refund from address.transfer to address.send to prevent queue jamming.
