### ISSUE TITLE
merge Submission and NewHeight events

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-contracts#131]
currently we are emitting 2 different events with duplicate data on period submission:
1. [operator](https://github.com/leapdao/leap-contracts/blob/449bc4309073a5358a9be841058f5bd4b054bedf/contracts/PoaOperator.sol#L152-L157)
2. [bridge](https://github.com/leapdao/leap-contracts/blob/449bc4309073a5358a9be841058f5bd4b054bedf/contracts/Bridge.sol#L22)

## Deliveries
- combine these into 1
- adjust node event listener and make sure it passes integration tests

## Purpose Alignment
- cheaper period submission

## Bounty

gardener: @johannbarbie | 10%
worker: | 75%
reviewer: | 15%

**Comment by sounak98** [comment]
@johannbarbie I am new to LeapDAO and would like to work on this issue.

**Comment by johannbarbie** [comment]
@sounak98 super cool. you are welcome to work on it. I'm happy to explain details in [our slack](https://docs.google.com/forms/d/e/1FAIpQLSd8_wDGDAi__HvfYEWNK_bvJzIkxwHHRVL6AFEfJewBd2Vn9A/viewform).

**Comment by sounak98** [comment]
Is this bounty completed now?

**Comment by johannbarbie** [comment]
imo the following needs to work:
1. Run node including this fix on old contracts
2. Submit period into old contracts
3. Upgrade contract
4. Submit period into new contracts
5. Double-check that period height in contract correct

**Comment by troggy** [comment]
@sounak98 👋how is it going?

**Comment by johannbarbie** [comment]
closed due to https://github.com/leapdao/leap-contracts/pull/209#issuecomment-503643501
