### ISSUE TITLE
remove consolidate tx type

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-contracts#136]
![image](https://user-images.githubusercontent.com/659301/52047075-8aea6180-2548-11e9-9b4b-a60afcec4450.png)

Operator (Bob) can create out of no-where (OON) txns, then spend that to Alice, then consolidate with Alice other UTXO. Giving it a lower priority than his other OON UTXOs.

**Comment by troggy** [comment]
closed via #137
