### ISSUE TITLE
Exit finalize fails on mainnet

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-contracts#140]
https://etherscan.io/tx/0xbb57339a2ac6dc61819ec8fe7b83e47367140199326a4b75ea568105dc770aad
https://leapdao.slack.com/archives/CFQH2UH3Q/p1549370976002200

**Comment by johannbarbie** [comment]
check the parity trace: https://etherscan.io/vmtrace?txhash=0xbb57339a2ac6dc61819ec8fe7b83e47367140199326a4b75ea568105dc770aad&type=parity

you will see that the priority queue returns 
`0x000000005c5db6d1000000000000000600be1ee37ac651d2362f43258768f866`
first 64 bits translate to `1549645521`
which is
`02/08/2019 @ 5:05pm (UTC)`

**Comment by johannbarbie** [comment]
in [this line](https://github.com/leapdao/leap-contracts/blob/master/contracts/ExitHandler.sol#L318):
`uint256 exitableAt = Math.max(timestamp + (2 * exitDuration), block.timestamp + exitDuration);`
usually the first expression will be higher `timestamp + (2 * exitDuration)`, and hence the exit date will be 2 * exitDuration in the future.

**Comment by johannbarbie** [comment]
solved and decreased exit duration
