### ISSUE TITLE
Write a contract upgrade to freeze deposits and exits (not master)

### ISSUE THREAD

**Issue by eshavkun** [leapdao/leap-contracts#163]
As part of migration to latest Tendermint version new mainnet will be built. This will includes suspension of deposits and exits on current mainnet and migrating UTXOs to a new mainnet. This bounty is about creating a new version of Exit Handler contract to disable (or allow freeze) of the deposits and exits and upgrading it on current mainnet

## Deliveries
*IMPORTANT: This contract should not be merged into Master!*
- Updated contract deployed on the current mainnet
- Fulfilled governance proposal to upgrade the contract

## Purpose Alignment
- To make sure no once makes deposits and exists during and after migration to the new mainnet

## Bounty

gardener: @eshavkun  | 15%
worker: @johannbarbie  | 70%
reviewer: @troggy  | 15%

**Comment by troggy** [comment]
Implemented here: https://github.com/leapdao/leap-contracts/pull/189/commits/e41bac2ed59649f7fc0ef64399a8ef04fa5d2830

**Comment by johannbarbie** [comment]
completed on mainnet
