### ISSUE TITLE
Write a contract upgrade to transfer minting rights

### ISSUE THREAD

**Issue by eshavkun** [leapdao/leap-contracts#164]
As part of migration to latest Tendermint version new mainnet will be built. This bounty is to write a new version of Swap Registry contract to transfer minting rights for LEAP token from cureent mainnet to a Swap Registry contract on the new mainnet

## Deliveries
**IMPORTANT: This contract should not be merged into Master!**
- Updated contract deployed on the current mainnet
- Fulfilled governance proposal to upgrade the contract

## Purpose Alignment
- To be able to use current LEAP tokens on new, migrated, mainnet

## Bounty

gardener: @eshavkun  | 15%
worker: @eshavkun  | 25%
worker: @johannbarbie  | 45%
reviewer: @troggy  | 15%

**Comment by troggy** [comment]
Implemented here: https://github.com/leapdao/leap-contracts/pull/189/commits/5352f486fb8a8f5735ea071adfd5bd95887f64b2

**Comment by johannbarbie** [comment]
completed on mainnet
