### ISSUE TITLE
startExit fails for spending condition output

### ISSUE THREAD

**Issue by pinkiebell** [leapdao/leap-contracts#184]
Trying to `startExit` with youngestInputIndex > 0 fails (wrong parsing?)

## Scope
- reproduce bug with the unit test. Use [integration test](https://github.com/leapdao/integration-tests/blob/27a3356ef640a6cda04fef580fab67c63de4817d/tests/8_breeding.js#L176) as an example
- fix the bug
- remove the workaround from integration tests

## Deliverables
- updated code 
- updated unit tests

## Gain for the project

People can exit their UTXOs!

## Roles
gardener: @troggy + @pinkiebell  / 50 DAI
worker: @troggy / 85% / 240 DAI
reviewer: @johannbarbie  / 15% / 60 DAI

## Funded by

Dev Circle

**Comment by johannbarbie** [comment]
simple way to reproduce: https://github.com/leapdao/integration-tests/blob/27a3356ef640a6cda04fef580fab67c63de4817d/tests/8_breeding.js#L176

**Comment by troggy** [comment]
![image](https://user-images.githubusercontent.com/163447/68540396-a1103280-03a2-11ea-9fb6-7b8772329504.png)

**Comment by troggy** [comment]
Looks like youngest input is not the case — [this little test](https://github.com/leapdao/leap-contracts/pull/252/commits/3a40d9926fd5826b2b4df6df9dad1789926f8c4c) works just fine.

**Comment by troggy** [comment]
Root cause: incorrect parsing of spendie tx in TxLib
Fixed here: https://github.com/leapdao/leap-contracts/pull/252
