### ISSUE TITLE
include exitsTokenData in Exit struct

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-contracts#197]

**Comment by troggy** [comment]
for NSTs ?

**Comment by johannbarbie** [comment]
yeah, the idea here is to get rid of this one: https://github.com/leapdao/leap-contracts/blob/master/contracts/ExitHandler.sol#L61
and include it in the `Exit` struct

**Comment by troggy** [comment]
@johannbarbie but token data is needed to finalize NST. How to deal with that?

**Comment by johannbarbie** [comment]
by adding `bytes32 data` into Exit struct here: https://github.com/leapdao/leap-contracts/blob/master/contracts/ExitHandler.sol#L42-L49

**Comment by troggy** [comment]
ah.. confused it with event. 👌
