### ISSUE TITLE
remove unused ExitStarted Event

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-contracts#198]

**Comment by troggy** [comment]
@johannbarbie wouldn't it be good to keep it for challengers to listen?

**Comment by johannbarbie** [comment]
either one of these 2 should always be emitted: https://github.com/leapdao/leap-contracts/blob/master/contracts/ExitHandler.sol#L25-L40
so that challengers can pick it up and challenge.

**Comment by troggy** [comment]
@johannbarbie do we need tokenData in the event? I'd say "no" as it breaks existing interfaces and can be read from the contract anyway

**Comment by johannbarbie** [comment]
yeah, i don't see why we included it. it is not used here: https://github.com/leapdao/leap-node/blob/7be3ccbe14a48f01abc52ca049b60abc96190945/src/eventsRelay.js#L97-L106

**Comment by troggy** [comment]
via #206
