### ISSUE TITLE
allow to challenge orphaned exits

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-contracts#208]
## Bounty

when an invalid period is included in the Plasma bridge, the CaS challenge game takes some amount of time to remove it again. during this time exits can be started based off the invalid period root. After the period root has been challenged, the previously started exits are orphaned, and need to be cleaned out. This will enable [step 9](https://docs.google.com/drawings/d/167EiEbZRi5cGH-Y3MYqa-DVaWRc-SLKth5jrZxsE1gA) in PoS challenges.

![Cryptoeconomic Agregate Signatures for Leap PoS (1)](https://user-images.githubusercontent.com/659301/60593037-328ee880-9da2-11e9-9994-fb8da7e3d855.png)

## Scope
- store periodRoot in `Exit` structs
- ~implement a `challengeExitRoot()` that takes the period root and re-checks if the root is still in the bridge. if not, the exit is canceled.~
- ignore exits that don't have a valid periodRoot in `finalizeExits()`

## Deliverables
- code
- tests

## Gain for the project
- ability to operate multiple validators

## Roles
bounty gardener: @johannbarbie / 10%
bounty worker: @johannbarbie / 60%
bounty reviewer: @troggy  / 30%

**Comment by troggy** [comment]
I guess we need a mapping periodRoot => UTXO in order to effectively execute step 9 on the contract side, right?

**Comment by troggy** [comment]
instead of adding periodRoot to Exit. Or I don't understand how we can use this data later when root is challenged

**Comment by johannbarbie** [comment]
> I guess we need a mapping periodRoot => UTXO in order to effectively execute step 9

the mapping can be kept off-chain. the contract only needs a way to decide if the exit is still valid or not. for that it takes the `periodRoot` from the exit and checks the bridge. if the root is still in, it remains valid, if the root has been deleted, the exit is canceled.

**Comment by johannbarbie** [comment]
i implemented this in a new way where i simply filter out all invalid exits on `finalizeExit()`
