### ISSUE TITLE
Use youngest input priority for plasma exits (MoreVP)

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-contracts#21]
# Bounty 8 : MoreVP

Implement MoreVP for better UX.

## Scope
- implement an ExitHandler contract the conforms to MoreVP on refactoring branch
- unit tests

## Deliverables
Branch is pushed to GitHub that solves the above.

## Gain for the project
It's good design.

----

https://github.com/omisego/research/blob/master/plasma/plasma-mvp/delegated-exits.md

chose a variant that will work for transactions to smart contracts as well

**Comment by johannbarbie** [comment]
pr here: https://github.com/parsec-labs/parsec-contracts/pull/35

**Comment by troggy** [comment]
related https://github.com/leapdao/leap-contracts/issues/29

**Comment by eezcjkr** [comment]
# Bounty 27 : MoreVP

Implement MoreVP for better UX.

## Scope
- implement an ExitHandler contract the conforms to MoreVP on refactoring branch
- unit tests

## Deliverables
Branch is pushed to GitHub that solves the above.

## Gain for the project
It's good design.

----
Bounties: https://github.com/parsec-labs/PIPs/wiki/Bounties

**Comment by johannbarbie** [comment]
@troggy what is missing on this one? need help?

**Comment by troggy** [comment]
inflight exits

**Comment by johannbarbie** [comment]
i would like to split this one. put the MoreVP tx-priority into driftwood milestone. while moving inflight exits to the raft. @troggy any objections to declare this bounty done, and opening a separate one for inflight exits?

**Comment by troggy** [comment]
no objections

**Comment by troggy** [comment]
Next part: https://github.com/leapdao/leap-contracts/issues/86
