### ISSUE TITLE
extend submitPeriod() with CaS bitmap

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-contracts#211]
# Bounty

before a period is submitted, validators will collect PERIOD_VOTE transactions on the tendermint chain. from these votes a bitmap will be constructed and submitted together with other data in `submitPeriod()`.

![Cryptoeconomic Agregate Signatures for Leap PoS (1)](https://user-images.githubusercontent.com/659301/60593037-328ee880-9da2-11e9-9994-fb8da7e3d855.png)

## Scope
- extend function signature.
- verify bitmap (if 1 bit get's challenged, bitmap should contain < 2/3 of `1` bits)
- insert into period root as [described here](https://docs.google.com/drawings/d/13oFjua-v_E_yaFYUbralluI-EysgtTaZb_sSgGbxG_A).

## Deliverables
- code
- tests

## Gain for the project
- ability to run multiple validators

## Roles
bounty gardener: @johannbarbie / 10%
bounty worker: @johannbarbie / 60%
bounty reviewer: name / 30%

**Comment by pinkiebell** [comment]
> verify bitmap (if 1 bit get's challenged, bitmap should contain < 2/3 of 1 bits)
Do you have a bit more information what this exaclty means ? :)

**Comment by johannbarbie** [comment]
> Do you have a bit more information what this exactly means ? :)

sry, didn't spot this on time. the idea is that there are so many bits flipped to true, than challenging one is enough to invalidate the whore period.

**Comment by pinkiebell** [comment]
This can happen as soon the validator who submits the cas lies all over the place. 
That is the problem with CAS, though. I guess we have to live with the fact

**Comment by johannbarbie** [comment]
@pinkiebell i've addressed your concern with this neat little function: https://github.com/leapdao/leap-contracts/blob/master/contracts/PoaOperator.sol#L178
so i hope

**Comment by pinkiebell** [comment]
> @pinkiebell i've addressed your concern with this neat little function: https://github.com/leapdao/leap-contracts/blob/master/contracts/PoaOperator.sol#L178
> so i hope

Ok, this basically means that assume that every validator slots should sign off ?
