### ISSUE TITLE
recover LEAP tokens from the old mainnet ExitHandler

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-contracts#215]
# Bounty

Once the [mainet migration](https://github.com/leapdao/meta/issues/83) is done, we will need to recover LEAP tokens from the old unused exit handler contract. To do that we will need to upgrade it to allow sweeping.

## Scope
- create a special version of ExitHandler with balance sweeping function (only for admin)
- upgrade the contract
- sweep the tokens to LeapDAO Escrow

## Deliverables
- sweepable ExitHandler contract (do not overwrite existing ExitHandler)
- all the LEAPs from the old exit handler contract (108078.321 LEAP) are transferred to LeapDAO Escrow

## Gain for the project
recover stuck funds, compensate LEAPs spent to bootstrap new mainnet

## Roles
bounty gardener: @troggy / 20%
bounty worker: name / 80%
bounty reviewer: reality

**Comment by johannbarbie** [comment]
can do

**Comment by johannbarbie** [comment]
deploying implementation: https://etherscan.io/tx/0x74e3599ef3ebaad289a6e4a53b478749473e0770214653405ae23e7e8d0119cc

**Comment by johannbarbie** [comment]
done here: https://etherscan.io/tx/0x9f1bfc330d4b8a88ce70c469a9a56d95cab98c9d85561d7eb69fb17ed2387ee3
