### ISSUE TITLE
upgrade testnet and mainnet with new governance.

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-contracts#223]
## Bounty

https://github.com/leapdao/leap-contracts/pull/221 and https://github.com/leapdao/leap-contracts/pull/222 allow token registration without governance duration. deploy the improvements to testnet and mainnet.

## Scope
- upgrade ExitHandler contract
- deploy new governance contract
- transfer `admin` of all proxies to new governance contract

## Deliverables
- done on testnet
- basic acceptance tests on testnet
- done on mainnet

## Gain for the project
- fast token registration

## Roles
bounty gardener: @johannbarbie / 20%
bounty worker: @troggy  / 80%

**Comment by troggy** [comment]
starting this one

**Comment by troggy** [comment]
Affected contracts:
- ExitHandler
- PoaOperator
- MinGov

Diff: https://github.com/leapdao/leap-contracts/compare/v1.1.0...master

**Comment by troggy** [comment]
Smoke testing on updated testnet:
- [ ] Deposit
- [ ] Exit
- [ ] Transfer
- [ ] Challenge Exit (with front-run protection)
- [ ] Challenge Exit with Spending Condition
