### ISSUE TITLE
Bounty Payout v2

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-contracts#248]
# Bounty

Improve on the previous Bounty Payout contract

## Scope
- check for minimum amount and make gardener mandatory
- allow multiple owners, so that only one contract can be used by all multi-sigs
- reduce call data so that initializing transactions is cheaper
- allow for reputation-only payments (in expectation of salary policy)

## Deliverables
- code
- tests

## Gain for the project
- faster payouts

## Roles
bounty gardener: @johannbarbie  / 10%
bounty worker: @johannbarbie  / 70%
bounty reviewer: @troggy  / 20%

**Comment by troggy** [comment]
> make gardener mandatory

objecting. I would make worker to be always mandatory

**Comment by johannbarbie** [comment]
> objecting. I would make worker to be always mandatory

i've changed the name to `payoutReviewedDelivery()`. better? :)
