### ISSUE TITLE
Contract upgrades for mainnet shutdown

### ISSUE THREAD

**Issue by zschavi** [leapdao/leap-contracts#282]
# Bounty
To shutdown the mainnet, we will need to recover LEAP token minting rights from the bridge.
To do that we will need to upgrade it to allow right transfer. After shutdown of mainnet we will want to sweep all the tokens that remain in the bridge contract. We will need to upgrade the exithandler contract.

## Scope
- create a special version of SwapRegistry with rights transfer function
- upgrade the contract
- transfer rights to LeapDAO generalMSG

- create a special version of ExitHandler with balance sweeping function (only for admin)
- upgrade the contract
- sweep the tokens to LeapDAO generalMSG

## Deliverables
- minting rights transferred to generalMSG
- sweepable ExitHandler contract (do not overwrite existing ExitHandler)

## Gain for the project
recover stuck funds & minting rights

## Roles
bounty gardener: @zschavi / 20%
bounty worker: @johannbarbie  / 80%
bounty reviewer: reality

**Comment by troggy** [comment]
Checked on etherscan 👍

✅SwapRegistry with minting rights transfer:
https://etherscan.io/address/0x8af6e56cc0fdcffe5e7242b18e2ca696a7c7b0a1

✅exit handler implementation which stops deposits and exits + allows to swipe all remaining tokens: https://etherscan.io/address/0x07658107cf02559a307cca6f2e63991387d479c3
