### ISSUE TITLE
required deposits for exits

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-contracts#52]

**Comment by eezcjkr** [comment]
Now need to modify the stake to be in ether as opposed to the native token.

**Comment by johannbarbie** [comment]
@eezcjkr are you on this, or is this open for grabs?

**Comment by troggy** [comment]
I think this is covered [here](https://github.com/leapdao/leap-contracts/pull/60/files#diff-b93cc8935074c3b8f5bb6ff859c3c1ccR22) by staking PSC
