### ISSUE TITLE
Create a separate exit game for inflight deposits

### ISSUE THREAD

**Issue by johba37** [leapdao/leap-contracts#72]
deposits create an event in the bridge contract. what if the operator does not include the transaction in the block or withholds the block?

## Scope 
- define a `depositInclusionTime` — reasonable number of periods to wait for deposit tx to be included. It should be changeable via governance.
- create `startDepositExit(depositId)` method for exiting inflight deposits (deposit without tx included in the period). It should create an exit with `depositId` instead of `utxo` part of priority.
- create `challengeDepositExit` to challenge invalid deposits. Challenger should present a proof of deposit tx inclusion. Provided deposit tx should not be younger than `exit + depositInclusionTime`
- make sure leap-node is working correctly with the change, picking up deposits as it should be

## Deliverables
- updated root chain contracts with the feature
- (probably) new leap-node release with necessary changes
- (probably) new leap-core release with necessary changes

## Gain for the project
- increased security for users — they will be able to exit their deposits even if the block with deposit tx was withheld (requires #85 for MoreVP exits)

## Roles: 
bounty gardener: @troggy /  5% 
bounty worker: @johannbarbie  / 85% 
bounty reviewer: @eezcjkr  / 10%

**Comment by troggy** [comment]
related #85

**Comment by troggy** [comment]
Probably, we can create a new period during deposit tx

**Comment by johannbarbie** [comment]
i still think creating periods out of sync with tendermint will halt bft consensus. how about:
- creating a `startDepositExit(depositId)` function
- use depositId at utxoId in exits mapping
- modify `challengeExit()` function to allow null objection for `_prevProof`
=> if `_prevProof == null`, use depositId to look up exit from mapping and challenge if values match.

The validator could attack this simple exit procedure by withholding a deposit, until the user registers an exit, and then include it and challenge with it. There is two ways to deal with it:
1. define a max period distance between deposit and inclusion of deposit tx which can only be used to challenge depositExits.
2. do nothing. the user will loose a stake, but will force the operator to include the deposit. which can be exited later on.

**Comment by troggy** [comment]
I agree, that having a special exit game for deposits is simpler.

Asfor a grieving attack, isn't it easily mitigated by enforcing that "challenging" tx (deposit tx) should be not younger than exit?

**Comment by johannbarbie** [comment]
> Asfor a grieving attack, isn't it easily mitigated by enforcing that "challenging" tx (deposit tx) should be not younger than exit?

exactly. it is allowed to be a bit younger (time it takes to include), but not much younger. that is what I meant in 1.

**Comment by eezcjkr** [comment]
Seems good to me.
