### ISSUE TITLE
Add a gap into inherited contracts

### ISSUE THREAD

**Issue by eshavkun** [leapdao/leap-contracts#87]
Add `uint256[50] private ______gap;` into inherited contracts to accommodate possible changes/resizings during upgrades (see openzeppelin-eth lib for example)

**Comment by troggy** [comment]
what is this about and it needs so many underscores dangling in front?

**Comment by eezcjkr** [comment]
This reserves 50 words worth of storage space in all the contracts that get inherited so that we can add additional variables in upgrades. Closing for https://github.com/leapdao/leap-contracts/pull/88
